cc_library(
    name = "scenes",
    srcs = [
        "capsules.cc",
        "cube_scene.cc",
        "scenes.cc",
        "scenes.h",
        "spheres.cc",
        "stars.cc",
    ],
    hdrs = ["scenes.h"],
    deps = [
        "//:base_hdrs",
        "//:scene"
    ],
    visibility = ["//visibility:public"],
    alwayslink = True,
)
